<?php

class qa_html_theme_layer extends qa_html_theme_base
{
    function head_script()
    {
        $this->content['script'][] = '<script src="' . qa_html(QA_HTML_THEME_LAYER_URLTOROOT) . 'main.js' . '"></script>';
        parent::head_script(); // TODO: Change the autogenerated stub
    }
}